// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
	endpoint "todo_SELF/auth/pkg/endpoint"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeRegisterHandler(m, endpoints, options["Register"])
	makeLoginHandler(m, endpoints, options["Login"])
	makeAccessHandler(m, endpoints, options["Access"])
	makeLogoutHandler(m, endpoints, options["Logout"])
	makeUserRegistrationAttemptHandler(m, endpoints, options["UserRegistrationAttempt"])
	makeFetchUsersHandler(m, endpoints, options["FetchUsers"])
	makeBlockUserHandler(m, endpoints, options["BlockUser"])
	makeUnblockUserHandler(m, endpoints, options["UnblockUser"])
	makeSearchUsersHandler(m, endpoints, options["SearchUsers"])
	makeDropUserHandler(m, endpoints, options["DropUser"])
	makeUpdateUserHandler(m, endpoints, options["UpdateUsers"])
	return m
}
