version: "2"
services:
  #8081
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth
    ports:
    #- 8800:8081
    - 8081:8081
    restart: always
    volumes:
    - .:/go/src/todo_SELF
    - /static:/static
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    #host: '127.0.0.1'
    ports:
      - '27100:27017'     
  redis:
    image: "redis:alpine"   
    restart: unless-stopped
    container_name: 'redis'
    ports:
      - '6379:6379'
  web:
    container_name: 'web'
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - './static:/usr/share/nginx/html'
    depends_on:
      - 'auth'    
