// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
	endpoint "todo_SELF/auth/pkg/endpoint"
	http1 "todo_SELF/auth/pkg/http"
	service "todo_SELF/auth/pkg/service"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"Access":                  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Access", logger))},
		"Login":                   {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Login", logger))},
		"Logout":                  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Logout", logger))},
		"Register":                {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "Register", logger))},
		"RegisterNewUserForm":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "RegisterNewUserForm", logger))},
		"UserLoginForm":           {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UserLoginForm", logger))},
		"UserRegisterForm":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UserRegisterForm", logger))},
		"UserRegistrationAttempt": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UserRegistrationAttempt", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["Register"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Register")), endpoint.InstrumentingMiddleware(duration.With("method", "Register"))}
	mw["Login"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Login")), endpoint.InstrumentingMiddleware(duration.With("method", "Login"))}
	mw["Access"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Access")), endpoint.InstrumentingMiddleware(duration.With("method", "Access"))}
	mw["Logout"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Logout")), endpoint.InstrumentingMiddleware(duration.With("method", "Logout"))}
	mw["UserRegistrationAttempt"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UserRegistrationAttempt")), endpoint.InstrumentingMiddleware(duration.With("method", "UserRegistrationAttempt"))}
	mw["RegisterNewUserForm"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "RegisterNewUserForm")), endpoint.InstrumentingMiddleware(duration.With("method", "RegisterNewUserForm"))}
	mw["UserLoginForm"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UserLoginForm")), endpoint.InstrumentingMiddleware(duration.With("method", "UserLoginForm"))}
	mw["UserRegisterForm"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UserRegisterForm")), endpoint.InstrumentingMiddleware(duration.With("method", "UserRegisterForm"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"Register", "Login", "Access", "Logout", "UserRegistrationAttempt", "RegisterNewUserForm", "UserLoginForm", "UserRegisterForm"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
